# Generated by Django 6.0.3 on 2026-05-02 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEstacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_paciente', models.CharField(max_length=10)),
                ('nombre_paciente', models.CharField(max_length=150)),
                ('patente', models.CharField(max_length=6)),
                ('fecha_hora_medica', models.DateTimeField(blank=True, null=True)),
                ('foto_hora_medica', models.ImageField(blank=True, null=True, upload_to='horas_medicas/')),
                ('movilidad_reducida', models.BooleanField(default=False)),
                ('es_urgencia', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En proceso'), ('EN_URGENCIA', 'En urgencia'), ('FINALIZADO', 'Finalizado')], default='PROGRAMADO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estacionamientos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Estacionamiento',
                'verbose_name_plural': 'Registros de Estacionamiento',
                'ordering': ['-creado_en'],
            },
        ),
    ]
