# Generated by Django 6.0.3 on 2026-06-15 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamientos', '0001_initial'),
        ('usuarios', '0002_alter_paciente_celular_alter_paciente_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroestacionamiento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='registroestacionamiento',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='estacionamientos', to='usuarios.paciente'),
            preserve_default=False,
        ),
    ]
